import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { redirect } from "next/navigation"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dumbbell, MapPin, ScanLine, Trophy, ArrowRight, Flame, Activity } from "lucide-react"

export default async function HomePage() {
  const session = await getServerSession(authOptions)

  // 1. If NOT logged in, show the Landing Page
  if (!session) {
    return (
      <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center p-6 text-center relative overflow-hidden">
        {/* Ambient Background */}
        <div className="absolute top-[-20%] right-[-10%] w-150 h-150 bg-red-600/20 blur-[150px] rounded-full pointer-events-none" />
        <div className="absolute bottom-[-20%] left-[-10%] w-150 h-150 bg-blue-600/10 blur-[150px] rounded-full pointer-events-none" />

        <div className="z-10 space-y-6 max-w-3xl">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-zinc-900 border border-zinc-800 text-sm text-zinc-400 mb-4">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-red-500"></span>
            </span>
            AI-Powered Fitness Revolution
          </div>
          
          <h1 className="text-6xl md:text-8xl font-black tracking-tighter">
            IRON <span className="text-transparent bg-clip-text bg-linear-to-r from-red-500 to-orange-600">LIFT</span>
          </h1>
          
          <p className="text-xl text-zinc-400 max-w-2xl mx-auto leading-relaxed">
            Your personal AI coach, nutritionist, and gym locator all in one. 
            Stop guessing. Start training with precision.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
            <Link href="/api/auth/signin">
              <Button className="h-14 px-8 text-lg bg-red-600 hover:bg-red-700 rounded-full font-bold shadow-[0_0_20px_rgba(220,38,38,0.5)] transition-all hover:scale-105">
                Start For Free <ArrowRight className="ml-2" />
              </Button>
            </Link>
            <Link href="/about">
              <Button variant="outline" className="h-14 px-8 text-lg border-zinc-800 bg-black/50 hover:bg-zinc-900 rounded-full text-zinc-300">
                Learn More
              </Button>
            </Link>
          </div>
        </div>
      </div>
    )
  }

  // 2. If LOGGED IN, show the "Command Center" Dashboard
  return (
    <div className="min-h-screen bg-black text-white p-6 md:p-12 relative overflow-hidden">
       {/* Ambient Background */}
       <div className="absolute top-0 left-0 w-full h-96 bg-linear-to-b from-zinc-900/50 to-black pointer-events-none" />
       
       <div className="max-w-7xl mx-auto relative z-10">
        
        {/* Header */}
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center mb-12 gap-6">
          <div>
            <h1 className="text-4xl font-bold mb-2">Hello, {session.user?.name?.split(" ")[0]} 👋</h1>
            <p className="text-zinc-400">Ready to crush your goals today?</p>
          </div>
          
          <div className="flex items-center gap-4 bg-zinc-900/50 border border-zinc-800 p-2 pr-6 rounded-full backdrop-blur-md">
            <div className="bg-red-600/20 p-2 rounded-full">
              <Flame className="text-red-500" size={24} />
            </div>
            <div>
              <p className="text-xs text-zinc-500 uppercase font-bold">Current Streak</p>
              <p className="text-xl font-black">0 Days</p>
            </div>
          </div>
        </header>

        {/* FEATURE GRID */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          
          {/* Card 1: AI Plan */}
          <Link href="/dashboard" className="group">
            <Card className="h-full bg-zinc-900 border-zinc-800 p-8 hover:border-red-600/50 transition-all hover:scale-[1.02] relative overflow-hidden">
              <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity">
                <Dumbbell size={120} />
              </div>
              <div className="bg-blue-600/20 w-14 h-14 rounded-2xl flex items-center justify-center mb-6 text-blue-500">
                <Activity size={28} />
              </div>
              <h3 className="text-2xl font-bold mb-2">My Plan</h3>
              <p className="text-zinc-400 mb-6">View your personalized workout and diet routine generated by AI.</p>
              <div className="flex items-center text-blue-400 font-bold group-hover:gap-2 transition-all">
                Go to Dashboard <ArrowRight size={18} className="ml-1" />
              </div>
            </Card>
          </Link>

          {/* Card 2: Gym Finder */}
          <Link href="/gyms" className="group">
            <Card className="h-full bg-zinc-900 border-zinc-800 p-8 hover:border-red-600/50 transition-all hover:scale-[1.02] relative overflow-hidden">
               <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity">
                <MapPin size={120} />
              </div>
              <div className="bg-green-600/20 w-14 h-14 rounded-2xl flex items-center justify-center mb-6 text-green-500">
                <MapPin size={28} />
              </div>
              <h3 className="text-2xl font-bold mb-2">Find Gyms</h3>
              <p className="text-zinc-400 mb-6">Locate the best rated gyms nearby with live OpenStreetMap data.</p>
              <div className="flex items-center text-green-400 font-bold group-hover:gap-2 transition-all">
                Explore Map <ArrowRight size={18} className="ml-1" />
              </div>
            </Card>
          </Link>

          {/* Card 3: Meal Scanner (NEW) */}
          <Link href="/scanner" className="group">
            <Card className="h-full bg-zinc-900 border-zinc-800 p-8 hover:border-red-600/50 transition-all hover:scale-[1.02] relative overflow-hidden">
               <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity">
                <ScanLine size={120} />
              </div>
              <div className="bg-red-600/20 w-14 h-14 rounded-2xl flex items-center justify-center mb-6 text-red-500">
                <ScanLine size={28} />
              </div>
              <h3 className="text-2xl font-bold mb-2">Iron Vision</h3>
              <p className="text-zinc-400 mb-6">Scan your food instantly to get macros and calorie counts using AI.</p>
              <div className="flex items-center text-red-400 font-bold group-hover:gap-2 transition-all">
                Launch Scanner <ArrowRight size={18} className="ml-1" />
              </div>
            </Card>
          </Link>

           {/* Card 4: Leaderboard/Progress (Future) */}
           <Link href="/generate" className="group md:col-span-3 lg:col-span-1">
            <Card className="h-full bg-linear-to-br from-zinc-900 to-zinc-950 border-zinc-800 p-8 hover:border-yellow-600/50 transition-all hover:scale-[1.02] relative overflow-hidden flex flex-col justify-center">
              <div className="flex items-center gap-4 mb-4">
                 <div className="bg-yellow-600/20 p-3 rounded-full text-yellow-500">
                   <Trophy size={24} />
                 </div>
                 <h3 className="text-xl font-bold">Regenerate Plan</h3>
              </div>
              <p className="text-zinc-400 text-sm">Need a change? Create a brand new routine from scratch.</p>
            </Card>
          </Link>

        </div>
       </div>
    </div>
  )
}